# This is a basic workflow to help you get started with Actions

name: Newman automate my collection of API requests

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      # No need to install Newman,npm,node as they already installed on the machine
      
      - name: Install dependences 
        run: npm install -g newman-reporter-htmlextra

      - name: Run Newman
        run: newman run Trello_APIs.postman_collection.json --env-var "key=${{secrets.key}}"    --env-var "token=${{secrets.token}}" -r "cli,json,junit,htmlextra" 
